### ISSUE TITLE
Baseline models

### ISSUE THREAD

**Issue by jshin49** [facebookresearch/accentor#3]
Hi, I was wondering if I could find the baseline model implementations.

Namely
- SimpleTOD
- SimpleTOD+
- Arranger
- Rewriter

**Comment by accreator** [comment]
Hi, Thanks for your interest and for reaching out! We have been working on open-sourcing these implementations (hopefully, they will be available by February). We will let you know when they are available.

**Comment by accreator** [comment]
The baselines are available now.
